---
title: "Spatio-temporal reconstruction of climate from pollen"
author: "John Tipton"
date: "7/26/2019"
output: ioslides_presentation
---

<style>
div#before-column p.forceBreak {
    break-before: column;
}
div#after-column p.forceBreak {
    break-after: column;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## {.columns-2}

<video width="400" height="500" controls muted="muted">
  <source src="pollen.mp4" type="video/mp4">
</video>

<p class="forceBreak"></p>

```{r, eval=TRUE, echo = FALSE, message = FALSE, warning = FALSE}
library(ggplot2)
library(here)
library(knitr)
library(BayesComposition)
library(fields)
knitr::opts_chunk$set(echo = FALSE, 
                      fig.align="center",
                      out.width = "85%", 
                      fig.width = 16,
                      fig.height = 9)
load("~/Google Drive/spatial-pollen/fit/fossil-prediction-elevation-nimble.RData")
load("~/Google Drive/spatial-pollen/fit/elevation-grid.RData")
N <- sqrt(nrow(Z_pred_full))
tt <- ncol(Z_pred_full)
n_grid <- nrow(pred.grid)
```



```{r, echo = FALSE}
Z_mean_full_mat <- Z_pred_full
for (t in 1:tt) {
  Z_mean_full_mat[, t] <- Z_mean_full
}
dat_pred <- data.frame(
  climate = c(Z_pred_full),
  # climate = c(X_mean_full),
  anomaly = c(Z_pred_full - Z_mean_full_mat) / sd(c(Z_pred_full - Z_mean_full_mat)),
  long    = rep(pred.grid[, 1], times=tt),
  lat     = rep(pred.grid[, 2], times=tt),
  year    = rep(1:tt, each=n_grid)
)
world <- map_data("world") # we already did this, but we can do it again
world <- subset(world, region %in% c("Italy", "Switzerland", "France"))
```



```{r reconstruction, fig.show='animate', cache=TRUE, message=FALSE, warning=FALSE, interval = 0.5, echo = FALSE}
zlims <- range(dat_pred$climate)
alims <- range(dat_pred$anomaly) 
for (t in 1:tt) {
  g_climate <- ggplot(data = subset(dat_pred, year==t),
                      aes(x = long, y = lat, fill = climate)) +
    geom_tile() +
    # geom_point(data = dat_fossil_climate, aes(x = long, y = lat, fill=X, color=X),
    #            size=0.25, alpha=1.0, inherit.aes=FALSE) +
    # scale_fill_continuous(low = "blue", high = "red", limits=zlims) +
    scale_fill_gradient2(low = "blue", mid="white", midpoint = sum(zlims)/2, 
                         high = "red", limits=zlims) +
        # scale_color_brewer(palette = "RdYlBu") +
    geom_path(data = world, aes(x = long, y = lat, group = group),
                 inherit.aes = FALSE,
                 color = "black") +
    coord_fixed(1.3) +
    xlim(4.5, 9.5) + 
    ylim(43.5, 47.5) + 
    xlab("Longitude") +
    ylab("Latitude") +
    ggtitle(paste("Estimated climate \n ", 250 * (t-1), "to",  250 * t, " \n years in the past")) +
    theme_bw() +
    theme(legend.position = "bottom",
          legend.text = element_text(size = 20),
          legend.key.width = unit(3, "cm"),
          axis.text = element_text(size = 28),
          title = element_text(size = 34, face = "bold", hjust = 0.5))
  
  g_anomaly <- ggplot(data = subset(dat_pred, year==t),
                      aes(x = long, y = lat, fill = anomaly)) +
    geom_tile() +
    # geom_point(data = dat_fossil_climate, aes(x = long, y = lat, fill=X, color=X),
    #            size=0.25, alpha=1.0, inherit.aes=FALSE) +
    # scale_fill_continuous(low = "blue", high = "red", limits=alims) +
    scale_fill_gradient2(low = "blue", mid = "white", midpoint = 0, 
                         high = "red", limits = alims) +
    # scale_color_continuous(pallette = "RdYlBu") + 
    geom_path(data = world, aes(x = long, y = lat, group = group),
                 inherit.aes = FALSE,
                 color = "black") +
    coord_fixed(1.3) +
    xlim(4.5, 9.5) + 
    ylim(43.5, 47.5) + 
    xlab("Longitude") +
    ylab("Latitude") +
    ggtitle(paste("Estimated anomaly \n ", 250 * (t-1), "to",  250 * t, " \n years in the past")) +
    theme_bw() +
    theme(legend.position = "bottom",
          legend.text = element_text(size = 20),
          legend.key.width = unit(3, "cm"),
          axis.text = element_text(size = 28),
          title = element_text(size = 34, face = "bold", hjust = 0.5))
  multiplot(g_climate, g_anomaly, cols=2)
  # print(g_climate)
  # print(multiplot(g_climate, g_anomaly, cols=2))
}
```
